<?php

use Drupal\Core\Cache\Cache;

/**
 * Implements hook_theme().
 */
function album_theme($existing, $type, $theme, $path) {
  return [
    'my_template' => [
      'variables' => ['test_var' => NULL],
    ],

    'album_form' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements cron function.
 */
function album_cron() {
  $cache_id = 'tag_user_id:4';
  Cache::invalidateTags([$cache_id]);
}
